project_id = "sutnggvyjstgykoyvgqs"

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.lipana-stk-push]
verify_jwt = false

[functions.lipana-webhook]
verify_jwt = false
